#!/usr/bin/env bash

if (( $# < 1 )) ; then
    echo "you must pass a source file to build"
    exit 1
fi

src=$1
bin=$(echo "$(basename ${src})" | cut -d '.' -f 1)

echo "building ${src} to ${bin} .. "

nasm -l num.lst -f elf64 -F dwarf -g ${src} -o art/${bin}.o && ld -o bin/${bin} art/${bin}.o
